### ISSUE TITLE
Migrate from NidukaAkalanka

### ISSUE THREAD

**Issue by POSTiGA1** [sing-web/x-ui#25]
Hello,

Thank you for your release.

Its possible to migrate from NidukaAkalanka to yours ?

Regard's

**Comment by Misaka-blog** [comment]
What's future do you want?

**Comment by POSTiGA1** [comment]
> 

Same Port - Multi User
same as NidukaAkalanka version

**Comment by Misaka-blog** [comment]
> > 
> 
> Same Port - Multi User same as NidukaAkalanka version

done
