### ISSUE TITLE
docker有问

### ISSUE THREAD

**Issue by xinkecn** [sing-web/x-ui#27]
你好，文档中提及的docker安装方式并没有提供reality的加密方式。经过尝试这个不需要域名证书的设置极为方便很适合，docker的方式。请问可以更新一下可用的docker镜像吗，包含reality协议的

**Comment by Misaka-blog** [comment]
到时候可以考虑下，现在在学校没空编译docker

**Comment by Misaka-blog** [comment]
近期的话我考虑将 x-ui 的 Docker 换成 Alpine，会更方便一些
