### ISSUE TITLE
question: Max Time Diff 最大时间差

### ISSUE THREAD

**Issue by POSTiGA1** [sing-web/x-ui#30]
Hello,

First of all thank you very much for your updates and great release,

May i ask what do "max time diff 最大时间差" in reality setting ?
![Screenshot_1](https://user-images.githubusercontent.com/60429190/232763488-70023eaf-729b-4036-b95f-eaa49d52afa0.png)

Regard's

**Comment by Misaka-blog** [comment]
You can read https://github.com/XTLS/REALITY for max time diff
