### ISSUE TITLE
配置tls时默认选择的加密套件auto无效

### ISSUE THREAD

**Issue by lgdlkq** [sing-web/x-ui#48]
在添加入站配置ws+tls时，密码加密套件部分默认选择的auto不起作用，必须手动删掉重新选择一次，否则配置完后会报错（config.json文件中"tlsSettings": {"cipherSuites": [""]}），导致xray无法运行。其他vless等同样如此。

**Comment by wesley0314** [comment]
+1
编辑已经创建的入站项目，删除加密选项中的`auto`后恢复正常

**Comment by Misaka-blog** [comment]
什么版本的，看看

**Comment by lgdlkq** [comment]
最新版，v0.3.3.8

**Comment by Misaka-blog** [comment]
> 最新版，v0.3.3.8

已修复，更新最新版x-ui即可
