### ISSUE TITLE
issue about user UUID log in the panel

### ISSUE THREAD

**Issue by epsilonzeio** [sing-web/x-ui#71]
Hi,
I'm using Hiddify panel as i'ts mentioned as one of the verified Web panels in Xcore main page repository.
But I faced an issue in my panel logs realizing that for each user& the UUID info is sent to a Hiddify automatic email. Please check the screenshots as below.

https://ibb.co/WfNCBxR
https://ibb.co/198nLtr
https://ibb.co/X7g43s3

As proxy webpanel is your field profession just want to be sure if is there any security or privacy issue about that.
It felt a warning about this issue.

**Comment by Misaka-blog** [comment]
But this is not hiddify panel, and you can review code

**Comment by epsilonzeio** [comment]
yes you're right. thanks.
